CREATE TABLE IF NOT EXISTS sessions (
    id           CHAR(72) PRIMARY KEY,
    session_data TEXT
);

CREATE TABLE IF NOT EXISTS test (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    body VARCHAR(255),
    timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS pc_room_log (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sequence VARCHAR(16) NOT NULL,
    name VARCHAR(8) NOT NULL,
    status BOOL NOT NULL,
    usage_rate INT UNSIGNED NOT NULL,
    capacity INT UNSIGNED NOT NULL,
    class_name VARCHAR(255) DEFAULT NULL,
    extra VARCHAR(255) DEFAULT NULL,
    timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS pc_room_now (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(8) NOT NULL,
    status BOOL NOT NULL,
    usage_rate INT UNSIGNED NOT NULL,
    capacity INT UNSIGNED NOT NULL,
    class_name VARCHAR(255) DEFAULT NULL,
    extra VARCHAR(255) DEFAULT NULL,
    timestamp TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
